# Generated by Django 3.1.1 on 2020-10-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201022_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.TextField(max_length=250),
        ),
    ]
